"""adjusted avaliability model

Revision ID: f195a3cfe8f8
Revises: d83d00379cc3
Create Date: 2023-09-27 18:25:24.656635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f195a3cfe8f8'
down_revision = 'd83d00379cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('monEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('tueStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('tueEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('wedStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('wedEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('thuStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('thuEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('friStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('friEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('satStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('satEndTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('sunStartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('sunEndTime', sa.Time(), nullable=False))
        batch_op.drop_column('startTime')
        batch_op.drop_column('endTime')
        batch_op.drop_column('dayOfWeek')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('clientId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('clientId',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dayOfWeek', sa.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('endTime', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('startTime', sa.TIME(), nullable=False))
        batch_op.drop_column('sunEndTime')
        batch_op.drop_column('sunStartTime')
        batch_op.drop_column('satEndTime')
        batch_op.drop_column('satStartTime')
        batch_op.drop_column('friEndTime')
        batch_op.drop_column('friStartTime')
        batch_op.drop_column('thuEndTime')
        batch_op.drop_column('thuStartTime')
        batch_op.drop_column('wedEndTime')
        batch_op.drop_column('wedStartTime')
        batch_op.drop_column('tueEndTime')
        batch_op.drop_column('tueStartTime')
        batch_op.drop_column('monEndTime')
        batch_op.drop_column('monStartTime')

    # ### end Alembic commands ###