"""create clients table

Revision ID: 4d09cb67933f
Revises: ffdc0a98111c
Create Date: 2023-09-16 13:29:49.214602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d09cb67933f'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancerId', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aboutMe', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('aboutMe')

    op.drop_table('clients')
    # ### end Alembic commands ###