"""create notes table

Revision ID: 018724e0c619
Revises: 4d09cb67933f
Create Date: 2023-09-16 14:33:59.612445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018724e0c619'
down_revision = '4d09cb67933f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freelancerId', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['clientId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancerId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###