"""updated booking model

Revision ID: 5d5d1d71b336
Revises: f195a3cfe8f8
Create Date: 2023-09-27 19:52:43.323165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5d1d71b336'
down_revision = 'f195a3cfe8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('endTime', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('endTime')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###